### ISSUE TITLE
今日の曜日を既定で選択、および強調表示したい

### ISSUE THREAD

**Issue by kurone-kito** [Azukimochi/TaAGatheringListSystem#15]
_分類: 機能追加_

### 概要

現在アセットの初期表示は以下のようになっています。

![スクリーンショット 2023-09-29 120021](https://github.com/Azukimochi/TaAGatheringListSystem/assets/44661432/6270ac0b-8feb-492a-8d8c-a6eaa490d23a)

ところで、VRChat 民は曜日感覚を忘れがちな方が一定数います。
これは時計アセットを併設することで解決可能ですが、本日の曜日に予めフォーカスすることで、本日のイベントを一目で把握できるようになるでしょう。

![スクリーンショット 2023-09-29 120100](https://github.com/Azukimochi/TaAGatheringListSystem/assets/44661432/785e8d35-939e-4b00-98e2-a68a381877e6)

また、別の曜日を選択した場合、本日の曜日がフォーカスカラーよりも弱く強調表示できるとより望ましいと考えます。

![スクリーンショット 2023-09-29 120139](https://github.com/Azukimochi/TaAGatheringListSystem/assets/44661432/fcc36d21-6d10-4d25-951a-aa88ba4f57a0)

### 課題

- 強調表示するにしてもカラーコードはどの辺が適正か
- bold 表示など、色以外の表現方法なども検討したい
- 0 時をまたぐと曜日が変わるので、その場合の挙動

**Comment by kurone-kito** [comment]
#14 と半分重複してしまいました。。🐱💦

**Comment by Azukimochi** [comment]
とりあえず現在日の取得タイミングはJSONのロード時で実装
カラーコードは親和性から一旦ダークグレーに

現在曜日：水曜日
選択曜日：火曜日　の状態
<img width="456" alt="image" src="https://github.com/Azukimochi/TaAGatheringListSystem/assets/103747350/21ffbbc4-a272-4bbe-8aa7-c9d51adf55bc">

**Comment by Azukimochi** [comment]
＞0 時をまたぐと曜日が変わるので、その場合の挙動
明示的なリロードボタンでリフレッシュがかかるので、一旦これで実装

定期的な再取得は別途Issueで実装しようかなと考えています

**Comment by Azukimochi** [comment]
>別の曜日を選択した場合、本日の曜日がフォーカスカラーよりも弱く強調表示できるとより望ましいと考えます。
 
これの解法として、設置者でおのおのカラーを変えられるよう、色設定をSerializeFieldから選択可能に
![image](https://github.com/Azukimochi/TaAGatheringListSystem/assets/103747350/1b5e48a7-b9e2-43eb-8805-540dace3c6f5)
