### ISSUE TITLE
【提案】今日の曜日を選択している色より弱めの色に設定

### ISSUE THREAD

**Issue by noricha-vr** [Azukimochi/TaAGatheringListSystem#23]
フォーカスが当たっている曜日を今日の曜日より弱めのほうが良いかなと思いました。
重なっている時はフォーカスが当たっている方を優先。

ただの提案なので必要なかったらクローズしてもらって大丈夫です。
<img width="351" alt="Screenshot 2023-10-25 at 18 03 59" src="https://github.com/Azukimochi/TaAGatheringListSystem/assets/110450172/6820e7fb-4085-4a91-aaa6-8fae801a2715">

**Comment by Azukimochi** [comment]
色についてはインスペクターから任意に変更可能なのですが、フォーカス優先で色を変更しておきました。
また、重なっている場合の動作もフォーカス優先のほうが確かに良さそうなので動作変更しました🙏
