### ISSUE TITLE
ユーザーによるカスタマイズを想定している設定をルート要素に集約したい

### ISSUE THREAD

**Issue by kurone-kito** [Azukimochi/TaAGatheringListSystem#27]
分類: 機能追加
関連: #15, #23

### 概要

現在、フォーカスしている曜日の色などは `Weeks` オブジェクトのコンポーネントにおける、インスペクターでカスタマイズ可能となっています。

![Weeks](https://github.com/Azukimochi/TaAGatheringListSystem/assets/44661432/efa0a2ea-4d24-417d-95b0-75e6df92fbde)

ユーザビリティの観点上、ユーザーによるカスタマイズを想定しているインスペクタ項目については、
ルート要素(例えば `TaAGatheringInfoSys`)に移設・集約した方が望ましく感じます。

### 懸念

- すでにカスタマイズしている人は、インスペクターの場所が移動することにより再設定が必要となるため、  
  この提案は Breaking changes になりうるかもしれません。

**Comment by Azukimochi** [comment]
おっしゃるとおり、カスタマイズ要素と設定項目を集約することは重要ですね

> Breaking changes になりうる

まさにこれが懸念点ではあります...。
ただ、普及がこれからというタイミングなので思い切って大きく変えるのはありかもしれません。

現状案としては、メインのコンポーネントのインスペクタに設定を集約し依存するのではなく、新しくSettingsコンポーネントを生やして各種設定を行い、各コンポーネントがこのSettingsを参照するような形が拡張性としていいのかなと

**Comment by Azukimochi** [comment]
Settingsオブジェクトにカスタム可能な情報を集約しました。
これで問題なければこのまま2.0.0としようと思います。

![image](https://github.com/Azukimochi/TaAGatheringListSystem/assets/103747350/7bdfabf0-745c-4cf7-84ad-d6d36338931b)
