### ISSUE TITLE
配布されているPrefabにライセンス表記がない

### ISSUE THREAD

**Issue by a1678991** [Azukimochi/TaAGatheringListSystem#29]
本システムはMITライセンスで提供されているようですが、同梱されているPrefabにはMITライセンスであるという記載やライセンスのコピーが見当たりません。

READMEの設置方法に従ってワールドをアップロードすると、自動的にワールドやアップロード者がMITライセンスに違反した状態となってしまうので、Prefab内へライセンス表記を追加してほしいです。

**Comment by Azukimochi** [comment]
MITライセンスの適用状態についてですが、最新の2.0.0配布のあとから適用したものとなるため、配布タイミングではGithub標準ライセンスとなっています。
MITライセンス適用後にアップデートを実施していないことが原因となるため、曖昧な状態としてしまったこと申し訳ありません。

2.0.1～MITライセンスを同梱することでMITライセンスの適用とし、本件の対応といたします。

**Comment by Azukimochi** [comment]
ライセンス表記をアセットに追加 #31 
![image](https://github.com/Azukimochi/TaAGatheringListSystem/assets/103747350/326654bd-e3a4-4e08-8df5-5d1fe926b08c)
