### ISSUE TITLE
同梱されているフォントのライセンスに違反している

### ISSUE THREAD

**Issue by a1678991** [Azukimochi/TaAGatheringListSystem#30]
このRepositoryにはMPLUS1-Boldというフォントファイルが含まれています。
また、配布されているPrefabでもTextコンポーネントから参照されているため、設置手順に従うと自動的にワールドのビルド結果にも含まれることになります。
しかし、こちらのフォントに関するライセンス表記がPrefabにもRepositoryにも見当たりません。

M+ FONTSの公式サイトを見る限りではOFLライセンスを採用していると記載されています。
> 新しい M+ FONTS は [SIL Open Font License](https://scripts.sil.org/OFL_web) で公開されています。
https://mplusfonts.github.io/

そして、OFLライセンスではフォントファイル自体の再配布を行う場合にはオリジナルのライセンスと著作権情報を含める必要があると記載されています。
> If you want to give the font files to others, you need to include all original license and copyright information.
https://openfontlicense.org/how-to-use-ofl-fonts/

私にはどちらも含まれているように見えないので、本Repository及び本アセットが設置されているすべてのワールドがライセンス違反状態になっている可能性が高いです。

**Comment by Azukimochi** [comment]
> そして、OFLライセンスではフォントファイル自体の再配布を行う場合にはオリジナルのライセンスと著作権情報を含める必要があると記載されています。  

こちら自分の見落としです。
再発防止に務めるとともに、次回の2.0.1にてライセンスファイルを同梱・ReadMeへ明記いたします。

**Comment by Azukimochi** [comment]
次のIssueと同様に対応 #29
