### ISSUE TITLE
技術、学術フィルター機能

### ISSUE THREAD

**Issue by noricha-vr** [Azukimochi/TaAGatheringListSystem#5]
タブ表示で技術、学術系のフィルターができると嬉しいな。

**Comment by Azukimochi** [comment]
### 技術・学術フィルタ実装
![image](https://github.com/Azukimochi/TaAGatheringListSystem/assets/103747350/9465229d-8b38-4635-984d-8d8de76da85e)
みやすさのために技術・学術で色分けもしてみました
